const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const subjects=[['Mathematics','➗'],['English Language','📖'],['Biology','🧬'],['Chemistry','⚗️'],['Physics','⚛️'],['History','🏛️'],['Geography','🌎'],['Computer Science','💻'],['SAT','🎯']];
const questionBank={
Mathematics:[['What is 12 × 8?',['86','96','108','88'],1],['If 2x + 4 = 10, what is x?',['2','3','4','6'],1],['What is 25% of 80?',['10','15','20','25'],2],['Which number is prime?',['21','27','29','33'],2],['What is the area of a rectangle 8 by 5?',['13','26','40','80'],2]],
'English Language':[['What is the main purpose of a thesis statement?',['To decorate a paragraph','To state the central claim','To list every source','To end an essay'],1],['Which word is a synonym for “brief”?',['Lengthy','Concise','Loud','Ancient'],1],['Which sentence uses a semicolon correctly?',['I studied; because I had a test.','I studied; I had a test.','I; studied for a test.','I studied because; I had a test.'],1],['What does evidence do in an argument?',['Supports a claim','Changes the topic','Removes the conclusion','Adds decoration'],0],['Which is the strongest topic sentence?',['School is a thing.','I have thoughts.','Daily reading can improve vocabulary and comprehension.','Books.'],2]],
Biology:[['Which organelle is known as the powerhouse of the cell?',['Nucleus','Ribosome','Mitochondrion','Cell wall'],2],['What molecule carries genetic instructions?',['DNA','ATP','Glucose','Water'],0],['Photosynthesis mainly occurs in which organelle?',['Chloroplast','Lysosome','Nucleus','Golgi apparatus'],0],['What is the basic unit of life?',['Atom','Cell','Tissue','Organ'],1],['Which gas do plants release during photosynthesis?',['Nitrogen','Carbon dioxide','Oxygen','Hydrogen'],2]],
Chemistry:[['What is the chemical symbol for oxygen?',['Ox','O','Og','Om'],1],['A substance with pH 2 is best described as…',['Acidic','Neutral','Basic','Metallic'],0],['How many protons does carbon have?',['4','6','8','12'],1],['Water is H₂O. How many hydrogen atoms are in one molecule?',['1','2','3','4'],1],['Which state has a fixed volume but takes the shape of its container?',['Solid','Liquid','Gas','Plasma'],1]],
Physics:[['What is the SI unit of force?',['Joule','Watt','Newton','Pascal'],2],['What is speed equal to?',['Distance × time','Distance ÷ time','Time ÷ distance','Mass ÷ volume'],1],['Which force pulls objects toward Earth?',['Friction','Magnetism','Gravity','Tension'],2],['Energy of motion is called…',['Potential energy','Kinetic energy','Thermal energy','Chemical energy'],1],['What happens to acceleration when net force increases while mass stays constant?',['It increases','It decreases','It becomes zero','It cannot change'],0]],
History:[['Which ancient civilization built the pyramids at Giza?',['Roman','Egyptian','Viking','Mayan'],1],['The Renaissance began in which region?',['Italy','Japan','West Africa','Australia'],0],['Which document begins with “We the People”?',['Declaration of Independence','U.S. Constitution','Magna Carta','Treaty of Paris'],1],['The Industrial Revolution first developed on a large scale in…',['Britain','Brazil','Egypt','Canada'],0],['What is a primary source?',['A later textbook summary','Evidence created during the period studied','A fictional story','A modern opinion'],1]],
Geography:[['What is the largest ocean on Earth?',['Atlantic','Indian','Arctic','Pacific'],3],['Which line divides Earth into Northern and Southern Hemispheres?',['Prime Meridian','Equator','Tropic of Cancer','International Date Line'],1],['What is a peninsula?',['Land surrounded by water on three sides','A deep ocean trench','A mountain range','A river delta'],0],['Which continent is the Sahara Desert in?',['Asia','Africa','Europe','South America'],1],['What is the capital of Japan?',['Kyoto','Seoul','Tokyo','Osaka'],2]],
'Computer Science':[['What does HTML primarily structure?',['Web page content','Wi-Fi signals','Hard-drive sectors','Battery chemistry'],0],['What does CSS primarily control?',['Page appearance','Database passwords','Internet cables','Computer power'],0],['What is an algorithm?',['A step-by-step procedure for solving a problem','A type of monitor','A password','A web browser'],0],['Which is a programming language?',['Python','JPEG','HDMI','Wi-Fi'],0],['What does a loop commonly do?',['Repeat instructions','Delete the keyboard','Turn off the internet','Print only once'],0]],
SAT:[['If 3x + 5 = 20, what is x?',['3','5','7','15'],1],['If y = 2x + 1 and x = 4, what is y?',['7','8','9','10'],2],['What is the slope of y = 3x + 2?',['2','3','5','6'],1],['A $50 item is discounted by 20%. What is the sale price?',['$30','$35','$40','$45'],2],['If a triangle has angles 50° and 60°, the third angle is…',['60°','70°','80°','90°'],1]]};
let currentSubject=null, currentQuestions=[], lessonIndex=0, score=0, missed=[];
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function renderSubjects(){ $('#subjects').innerHTML=subjects.map(([n,i])=>`<button class="subject" data-subject="${escapeHtml(n)}"><div class="icon">${i}</div><b>${n}</b><span class="small">5-question lesson</span></button>`).join(''); $$('.subject').forEach(x=>x.onclick=()=>startLesson(x.dataset.subject));}
function startLesson(s){currentSubject=s;currentQuestions=questionBank[s].map((q,i)=>({q:q[0],a:q[1],correct:q[2],index:i}));lessonIndex=0;score=0;missed=[];renderQuestion();}
function renderQuestion(){const el=$('#lesson'),item=currentQuestions[lessonIndex];el.classList.remove('hidden');el.innerHTML=`<div class="lesson-top"><div><span class="eyebrow">LESSON + TEST</span><h3>${escapeHtml(currentSubject)}</h3></div><span class="progress-pill">${lessonIndex+1} / ${currentQuestions.length}</span></div><p>Review the key idea, then choose the best answer. You’ll see corrections for anything you miss.</p><div class="lesson-q">${escapeHtml(item.q)}</div><div class="answers">${item.a.map((a,i)=>`<button data-a="${i}">${escapeHtml(a)}</button>`).join('')}</div><p id="result" class="small">Question ${lessonIndex+1} of ${currentQuestions.length}</p>`;$$(".answers button").forEach(b=>b.onclick=()=>answerQuestion(+b.dataset.a));el.scrollIntoView({behavior:'smooth',block:'start'});}
function answerQuestion(choice){const item=currentQuestions[lessonIndex],buttons=$$('.answers button');buttons.forEach(b=>b.disabled=true);const ok=choice===item.correct;buttons[choice].classList.add(ok?'correct':'wrong');buttons[item.correct].classList.add('correct');if(ok)score++;else missed.push(item);$('#result').textContent=ok?'Correct! 🎉 Great job.':'Not quite. The highlighted answer is correct.';setTimeout(()=>nextQuestion(),650);}
function nextQuestion(){lessonIndex++;if(lessonIndex<currentQuestions.length){renderQuestion();return;}showSummary();}
function showSummary(){const el=$('#lesson'),pct=Math.round(score/currentQuestions.length*100);const misses=missed.length;el.innerHTML=`<div class="eyebrow">LESSON COMPLETE</div><h3>${escapeHtml(currentSubject)}</h3><div class="score-card"><strong>${score}/${currentQuestions.length}</strong><span>${pct}%</span></div><p>${misses?`You missed ${misses} question${misses===1?'':'s'}. Review the corrections below, then retest only those questions.`:'Excellent work — you answered every question correctly!'}</p>${misses?`<div class="corrections">${missed.map(x=>`<div class="correction"><b>${escapeHtml(x.q)}</b><p>Correct answer: <strong>${escapeHtml(x.a[x.correct])}</strong></p><span>Tip: explain why this answer works in your own words before moving on.</span></div>`).join('')}</div>`:''}<button class="primary" id="lessonAction">${misses?'Retest missed questions':'Finish lesson'}</button>`;$('#lessonAction').onclick=()=>misses?retestMissed():$('#lesson').classList.add('hidden');}
function retestMissed(){currentQuestions=missed.slice();missed=[];lessonIndex=0;score=0;renderQuestion();}
$$('[data-nav]').forEach(b=>b.onclick=()=>{$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.nav).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});});
renderSubjects();
$('#material').onchange=e=>{const f=e.target.files[0];if(!f)return;const list=JSON.parse(localStorage.getItem('focuslyMaterials')||'[]');list.push({name:f.name,size:f.size,date:new Date().toLocaleString()});localStorage.setItem('focuslyMaterials',JSON.stringify(list.slice(-10)));renderMaterials();};
function renderMaterials(){const list=JSON.parse(localStorage.getItem('focuslyMaterials')||'[]');$('#materialList').innerHTML=list.length?list.map((x,i)=>`<div class="material-chip">📎 ${escapeHtml(x.name)} <button data-remove-material="${i}" aria-label="Remove ${escapeHtml(x.name)}">×</button></div>`).join(''):'<span class="small">No study material added yet.</span>';$$("[data-remove-material]").forEach(b=>b.onclick=()=>{const l=JSON.parse(localStorage.getItem('focuslyMaterials')||'[]');l.splice(+b.dataset.removeMaterial,1);localStorage.setItem('focuslyMaterials',JSON.stringify(l));renderMaterials();});}renderMaterials();
// Drawing canvas
const canvas=$('#canvas'),ctx=canvas.getContext('2d');function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),old=canvas.toDataURL();canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);if(old!=='data:,'){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,r.width,r.height);img.src=old;}}resizeCanvas();addEventListener('resize',resizeCanvas);let drawing=false,last=null;function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}canvas.addEventListener('pointerdown',e=>{drawing=true;last=point(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);ctx.strokeStyle='#8b7cf6';ctx.lineWidth=+$('#brush').value;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p});['pointerup','pointercancel','pointerleave'].forEach(ev=>canvas.addEventListener(ev,()=>drawing=false));$('#clearCanvas').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height);$('#brush').oninput=e=>$('#brushValue').textContent=`${e.target.value} px`;
// Timer
let seconds=1500,timer=null;function showTimer(){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`;};function startTimer(){if(timer)return;timer=setInterval(()=>{seconds--;showTimer();if(seconds<=0){clearInterval(timer);timer=null;seconds=1500;showTimer();stopBeat();alert('Focus session complete! 🎉')}} ,1000);$('#timerBtn').textContent='Pause focus';startBeat();}function pauseTimer(){if(!timer)return;clearInterval(timer);timer=null;$('#timerBtn').textContent='Resume focus';}$('#timerBtn').onclick=()=>timer?pauseTimer():startTimer();$('#resetTimer').onclick=()=>{if(timer)clearInterval(timer);timer=null;seconds=1500;showTimer();$('#timerBtn').textContent='Start 25-minute focus'};showTimer();
// Calm synthesized beat
let audioCtx=null,master=null,beatTimer=null;function initAudio(){if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=+$('#volume').value;master.connect(audioCtx.destination)}}function pulse(t,f=120,d=.14,g=.045){const o=audioCtx.createOscillator(),a=audioCtx.createGain();o.type='sine';o.frequency.value=f;a.gain.setValueAtTime(.0001,t);a.gain.exponentialRampToValueAtTime(g,t+.015);a.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(a);a.connect(master);o.start(t);o.stop(t+d+.04)}function beat(){initAudio();const t=audioCtx.currentTime;pulse(t,110,.18,.055);pulse(t+.5,82,.22,.025);pulse(t+1,110,.18,.045)}function startBeat(){initAudio();if(audioCtx.state==='suspended')audioCtx.resume();if(!beatTimer){beat();beatTimer=setInterval(beat,1000);$('#beatBtn').textContent='Pause calm beat';$('#audioToggle').textContent='🔊'}}function stopBeat(){if(beatTimer)clearInterval(beatTimer);beatTimer=null;$('#beatBtn').textContent='Start calm beat';$('#audioToggle').textContent='🔇'}$('#beatBtn').onclick=()=>beatTimer?stopBeat():startBeat();$('#audioToggle').onclick=()=>beatTimer?stopBeat():startBeat();$('#volume').oninput=e=>{if(master)master.gain.value=+e.target.value};$('#continueBtn').onclick=()=>{$('#headphones').classList.add('hidden');startBeat()};
// Buddy: safe drag bounds, minimize state, expressive animation
const buddy=$('#buddy'),robot=$('#buddyRobot');let drag=false,offset={x:0,y:0};function clampBuddy(){const r=buddy.getBoundingClientRect(),pad=8;let left=Math.min(Math.max(pad,r.left),innerWidth-r.width-pad);let top=Math.min(Math.max(70,r.top),innerHeight-r.height-82);buddy.style.left=left+'px';buddy.style.top=top+'px';buddy.style.right='auto';buddy.style.bottom='auto'}function dragStart(e){if(e.target.closest('button,input,select'))return;drag=true;const r=buddy.getBoundingClientRect();offset={x:e.clientX-r.left,y:e.clientY-r.top};robot.setPointerCapture(e.pointerId);robot.classList.add('dragging')}robot.addEventListener('pointerdown',dragStart);robot.addEventListener('pointermove',e=>{if(!drag)return;let left=e.clientX-offset.x,top=e.clientY-offset.y;left=Math.max(8,Math.min(innerWidth-buddy.offsetWidth-8,left));top=Math.max(68,Math.min(innerHeight-buddy.offsetHeight-88,top));buddy.style.left=left+'px';buddy.style.top=top+'px';buddy.style.right='auto';buddy.style.bottom='auto'});['pointerup','pointercancel'].forEach(ev=>robot.addEventListener(ev,()=>{drag=false;robot.classList.remove('dragging');clampBuddy()}));addEventListener('resize',clampBuddy);
$('#buddyToggle').onclick=()=>{$('#buddy').classList.toggle('open');$('#buddy').classList.remove('minimized');clampBuddy()};$('#buddyMinimize').onclick=()=>$('#buddy').classList.toggle('minimized');
$('#nickname').value=localStorage.getItem('focuslyNickname')||'Buddy';$('#nickname').onchange=e=>localStorage.setItem('focuslyNickname',e.target.value.trim()||'Buddy');
function getVoices(){return speechSynthesis.getVoices().filter(v=>/^en/i.test(v.lang))}function voices(){const vs=getVoices();$('#voice').innerHTML=vs.map((v,i)=>`<option value="${i}">${escapeHtml(v.name.replace(/Microsoft |Google |Apple /,'').replace(/ Online.*$/,''))}</option>`).join('')||'<option value="0">Device default</option>'}voices();speechSynthesis.onvoiceschanged=voices;
function setMood(m){robot.dataset.mood=m;clearTimeout(robot._moodTimer);robot._moodTimer=setTimeout(()=>robot.dataset.mood='idle',m==='thinking'?2200:1400)}
function speak(text){if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text),vs=getVoices(),idx=+$('#voice').value;if(vs[idx])u.voice=vs[idx];u.rate=.95;u.pitch=1.2;u.onstart=()=>setMood('talking');u.onend=()=>setMood('happy');u.onerror=()=>setMood('idle');speechSynthesis.cancel();speechSynthesis.speak(u)}
function buddyReply(text){const n=($('#nickname').value||'Buddy').trim()||'Buddy',t=text.toLowerCase();let reply;if(!t)reply=`Hey! I'm ${n}. Tell me what you need.`;else if(/^(hi|hello|hey)\b/.test(t)||/how are you/.test(t))reply=`Hey! I'm ${n}, and I'm ready to help. What are you studying?`;else if(/\b(math|equation|algebra|calculate|solve)\b/.test(t))reply=`Absolutely. Send me the full math problem and I'll help you work through it step by step.`;else if(/\b(study|focus|exam|test|homework)\b/.test(t))reply=`Let's make it manageable: choose one small task, work for a short focused block, then test what you remember.`;else if(/\b(sad|stressed|tired|overwhelmed)\b/.test(t))reply=`Take a breath. You don't have to solve everything at once. Let's choose the next small step together.`;else if(/\b(water|drink)\b/.test(t))reply=`Good reminder. Take a quick water break, then come back when you're ready.`;else reply=`I hear you. I can help you think it through. Tell me the goal, what you already know, and where you're stuck.`;$('#buddyStatus').textContent=reply;setMood('happy');speak(reply);return reply}
$('#speakBuddy').onclick=()=>speak($('#buddyStatus').textContent);$('#sendBuddy').onclick=()=>{const v=$('#buddyInput').value.trim();if(v){buddyReply(v);$('#buddyInput').value=''}};$('#buddyInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#sendBuddy').click()});
// Shared speech recognizer so Buddy and Ask cannot overwrite each other's handlers.
let recognition=null,recognitionMode=null;if('SpeechRecognition'in window||'webkitSpeechRecognition'in window){const R=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new R();recognition.continuous=false;recognition.interimResults=false;recognition.lang='en-US';recognition.onstart=()=>setMood('listening');recognition.onend=()=>{setMood('idle');const mode=recognitionMode;recognitionMode=null;if(mode==='wake'&&wakeEnabled)setTimeout(()=>startListening('wake'),500)};recognition.onerror=()=>{setMood('idle');const mode=recognitionMode;recognitionMode=null;if(mode==='wake'&&wakeEnabled)setTimeout(()=>startListening('wake'),900)};recognition.onresult=e=>{const text=e.results[0][0].transcript.trim();if(recognitionMode==='ask'){$('#question').value=text;sendQuestion()}else if(recognitionMode==='buddy'){const cleaned=text.replace(/^(hey\s+)?buddy\b[,:]?\s*/i,'').trim();$('#buddyInput').value=cleaned;buddyReply(cleaned||'hello')}else if(recognitionMode==='wake'){const low=text.toLowerCase();const name=($('#nickname').value||'Buddy').trim().toLowerCase();const hit=low.includes('hey buddy')||low.includes('buddy')||low.includes(name);if(hit){const cleaned=text.replace(new RegExp('^(hey\\s+)?'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b[,:]?\\s*','i'),'').trim();buddyReply(cleaned||'hello')}}}}
function startListening(mode){if(!recognition){alert('Voice input is not supported by this browser. You can still type naturally.');return}recognitionMode=mode;try{recognition.start()}catch(e){recognitionMode=null}}
$('#listenBuddy').onclick=()=>startListening('buddy');$('#micAsk').onclick=()=>startListening('ask');
// Optional wake-word listening is opt-in; browsers such as iOS Safari do not permit reliable always-on background listening.
let wakeEnabled=false;function toggleWake(){wakeEnabled=!wakeEnabled;$('#wakeBuddy').textContent=wakeEnabled?'⏹ Stop wake word':'✨ Wake word';$('#buddyStatus').textContent=wakeEnabled?'Listening for “Hey Buddy” while this page is open…':'Wake-word listening is off. Tap Listen or type to Buddy.';if(wakeEnabled)startListening('wake')}
$('#wakeBuddy').onclick=toggleWake;
// Study Helper: useful offline answers without falsely claiming a cloud AI backend.
function sendQuestion(){const q=$('#question').value.trim();if(!q)return;$('#chatLog').insertAdjacentHTML('beforeend',`<div class="bubble user"></div>`);$('#chatLog').lastElementChild.textContent=q;setTimeout(()=>{let a=studyAnswer(q);$('#chatLog').insertAdjacentHTML('beforeend',`<div class="bubble bot"></div>`);$('#chatLog').lastElementChild.textContent=a;$('#chatLog').scrollTop=999999},180);$('#question').value=''}
function studyAnswer(q){const t=q.toLowerCase();if(/photosynthesis/.test(t))return'Photosynthesis is how plants convert light energy into chemical energy. In simple terms, carbon dioxide + water + light energy are used to make glucose, and oxygen is released.';if(/quadratic/.test(t))return'For a quadratic equation, first try factoring. If it does not factor easily, you can use the quadratic formula: x = (−b ± √(b² − 4ac)) / 2a.';if(/thesis/.test(t))return'A strong thesis states the central claim or position of an essay. It should be specific enough to guide the reader and the rest of the paper.';if(/newton|force/.test(t))return'Newton’s second law is F = ma: net force equals mass multiplied by acceleration. If you know any two of the three values, you can solve for the third.';if(/study|memorize|remember/.test(t))return'Try active recall: close your notes, explain the idea from memory, check what you missed, and retest yourself later. Spaced repetition makes the review stick longer.';if(/\b(sat|test|exam)\b/.test(t))return'For exam prep, mix short timed practice with review of mistakes. Keep an error log and retest missed question types rather than only repeating questions you already know.';if(/\b(hello|hi|hey)\b/.test(t))return'Hi! Ask me a schoolwork question, paste a problem, or tell me what topic you want to review.';return'I can help with common school topics in Offline Study Helper mode. Try including the subject and the exact question, for example: “Explain Newton’s second law with an example.”'}$('#sendAsk').onclick=sendQuestion;$('#question').addEventListener('keydown',e=>{if(e.key==='Enter')sendQuestion()});
// Timetable stored locally
const defaultSchedule=[{title:'Math practice',time:'16:00',type:'Study'},{title:'Science review',time:'17:00',type:'Study'},{title:'Water break',time:'18:00',type:'Water break'},{title:'SAT practice',time:'19:00',type:'SAT'}];let schedule=JSON.parse(localStorage.getItem('focuslySchedule')||'null')||defaultSchedule;function saveSchedule(){localStorage.setItem('focuslySchedule',JSON.stringify(schedule))}function renderSchedule(){const el=$('#schedule');if(!schedule.length){el.innerHTML='<div class="empty">No sessions yet. Add one above.</div>';return}el.innerHTML=schedule.slice().sort((a,b)=>a.time.localeCompare(b.time)).map((x,i)=>`<div><span><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.type)}</small></span><b>${formatTime(x.time)}</b><button class="delete-session" data-i="${i}" aria-label="Delete ${escapeHtml(x.title)}">×</button></div>`).join('');$$('.delete-session').forEach(b=>b.onclick=()=>{schedule.splice(+b.dataset.i,1);saveSchedule();renderSchedule()})}function formatTime(t){const [h,m]=t.split(':').map(Number),amp=h>=12?'PM':'AM',hh=h%12||12;return`${hh}:${String(m).padStart(2,'0')} ${amp}`}renderSchedule();
$('#addSession').onclick=()=>$('#sessionModal').classList.remove('hidden');$('#closeSession').onclick=()=>$('#sessionModal').classList.add('hidden');$('#saveSession').onclick=()=>{const title=$('#sessionTitle').value.trim(),time=$('#sessionTime').value||'16:00',type=$('#sessionType').value;if(!title){alert('Please add a session name.');return}schedule.push({title,time,type});saveSchedule();renderSchedule();$('#sessionTitle').value='';$('#sessionModal').classList.add('hidden')};
let reminderEnabled=localStorage.getItem('focuslyReminders')==='yes';function updateReminderUI(){const s=$('#reminderStatus');s.textContent=reminderEnabled?' Reminders enabled on this device.':' Reminders are off.'}updateReminderUI();$('#enableReminders').onclick=async()=>{if(!('Notification'in window)){alert('This browser does not support notifications.');return}const p=await Notification.requestPermission();if(p==='granted'){reminderEnabled=true;localStorage.setItem('focuslyReminders','yes');updateReminderUI();alert('Reminders are enabled while this page is open.')}else alert('Notifications were not enabled. You can still use the timetable without them.');};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
// Start Buddy in a safe, compact state and keep it within the viewport.
$('#buddy').classList.add('open');if(innerWidth<600)$('#buddy').classList.add('minimized');requestAnimationFrame(clampBuddy);
